name: Clean Packages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *" 

jobs:
  clean-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'blog2-api'
          package-type: 'container'
          min-versions-to-keep: 10
      - uses: actions/delete-package-versions@v4
        with: 
          package-name: 'blog2-web'
          package-type: 'container'
          min-versions-to-keep: 10
